Switch to spring-boot 2.4.4 version
The 2.5.0-M3 changed the way how 'data.sql' file processing is performed
therefore it doesn't work and fails with:

  org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CATEGORY" not found;

Switching to 2.4.4 makes it work again.